---
- name: Testing andrewrothstein.tor
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'tor --version'
      ansible.builtin.command: tor --version
      changed_when: false
      register: tor_test_output
    - name: Output from 'tor --version'
      ansible.builtin.debug:
        msg: '{{ tor_test_output.stdout }}'
