---
- include_role:
    name: andrewrothstein.bash
- include_role:
    name: andrewrothstein.git
- include_role:
    name: andrewrothstein.gcc_toolbox
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: install os dep pkgs...
  become: true
  become_user: root
  package:
    name: '{{ tor_dep_os_pkgs | default([]) }}'
    state: present

- name: look for install
  become: true
  stat:
    path: /usr/local/bin/tor
xs  changed_when: false
  register: tor_binary

- when: not tor_binary.stat.exists
  block:
    - name: git clone {{ tor_git }}:{{ tor_name }}
      become: true
      become_user: root
      git:
        repo: '{{ tor_git }}'
        dest: '{{ tor_src_dir }}'
        version: '{{ tor_name }}'

    - name: autogen.sh ({{ tor_src_dir }})
      become: true
      become_user: root
      command: sh -l {{ tor_src_dir }}/autogen.sh
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_src_dir }}/configure'

    - name: configure...
      become: true
      become_user: root
      command: '{{ tor_src_dir }}/configure --disable-asciidoc'
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_src_dir }}/Makefile'

    - name: make ({{ tor_src_dir }})
      become: true
      become_user: root
      command: make
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_src_dir }}/src/tor/tor'

    - name: make install ({{ tor_src_dir }})
      become: true
      become_user: root
      command: make install
      args:
        chdir: '{{ tor_src_dir }}'
        creates: /usr/local/bin/tor
  always:
    - name: rm -rf {{ tor_src_dir }}
      become: true
      become_user: root
      file:
        path: '{{ tor_src_dir }}'
        state: absent
