---
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Installing andrewrothstein.git
  ansible.builtin.include_role:
    name: andrewrothstein.git
- name: Installing andrewrothstein.gcc_toolbox
  ansible.builtin.include_role:
    name: andrewrothstein.gcc_toolbox
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'

- name: Install os dep pkgs...
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ tor_dep_os_pkgs | default([]) }}'
    state: present

- name: Cloning {{ tor_git }} version {{ tor_name }} to {{ tor_src_dir }}
  become: true
  become_user: root
  ansible.builtin.git:
    repo: '{{ tor_git }}'
    dest: '{{ tor_src_dir }}'
    version: '{{ tor_name }}'
    depth: 1

- name: Looking for tor executable at {{ tor_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ tor_exe }}'
  changed_when: false
  register: tor_binary

- name: Building tor from {{ tor_src_dir }}
  when: not tor_binary.stat.exists
  block:

    - name: Executing '{{ tor_autogen_cmd }}'
      become: true
      become_user: root
      ansible.builtin.command: '{{ tor_autogen_cmd }}'
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_src_dir }}/configure'

    - name: Executing '{{ tor_configure_cmd }}'
      become: true
      become_user: root
      ansible.builtin.command: '{{ tor_configure_cmd }}'
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_src_dir }}/Makefile'

    - name: Executing '{{ tor_make_cmd }}'
      become: true
      become_user: root
      ansible.builtin.command: '{{ tor_make_cmd }}'
      args:
        chdir: '{{ tor_src_dir }}'
        creates: '{{ tor_exe }}'
    - name: Executing '{{ tor_make_install_cmd }}'
      become: true
      become_user: root
      ansible.builtin.command: '{{ tor_make_install_cmd }}'
      args:
        chdir: '{{ tor_src_dir }}'
        creates: /usr/local/bin/tor
